# Generated by Django 4.0.5 on 2022-06-07 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0002_alter_images_image_comments_alter_images_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('profile_bio', models.CharField(max_length=10000)),
                ('profile_image', models.ImageField(upload_to='instagram/')),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='image_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instapp.profile'),
        ),
    ]
